version: "3.9"
services:
  web-ui:
    container_name: web-ui
    build:
      context: web-ui
      target: 'develop-stage'
    ports:
      - '8000:8080'
    volumes:
      - '.:/app'
    command: >
      sh -c "cd web-ui && yarn install && quasar dev"
    depends_on:
      - app

  app:
    container_name: app
    image: app-spring-test
    build: spring-test
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING.JPA.PROPERTIES.HIBERNATE.DIALECT=org.hibernate.dialect.PostgreSQLDialect
      - SPRING.JPA.PROPERTIES.HIBERNATE.JDBC.LOB.NON_CONTEXTUAL_CREATION=true
      - SPRINGDOC.API-DOCS.PATH=/api-docs
      - SPRINGDOC.SWAGGER-UI.OPERATIONSSORTER=method
      - SPRING.SECURITY.USER.NAME=mike
      - SPRING.SECURITY.USER.PASSWORD=mike

  db:
    image: postgres
    container_name: db
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres